spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  application:
    name: unii.arc
  redis:
    host: 127.0.0.1
    
server:
  port: 8764
  
management.security.enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.host:localhost}:${eureka.port:8761}/eureka/
      
feign.hystirx.enable: true

security:
  oauth2:
    resource:
      id: unii.arc
      user-info-uri: http://localhost:8080/uaa/user
      prefer-token-info: false

logging.level.org.springframework.security: DEBUG